# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180119_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deallog',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter', verbose_name='章节'),
        ),
    ]
