# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 15:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180119_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0, help_text='余额', verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='account',
            name='present',
            field=models.FloatField(default=0, help_text='赠币', verbose_name='赠币'),
        ),
        migrations.AlterField(
            model_name='account',
            name='recharge',
            field=models.FloatField(default=0, help_text='充值币', verbose_name='充值币'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='book',
            field=models.ForeignKey(help_text='图书对应 ID', on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='buy_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='购买时间', verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='buy_type',
            field=models.IntegerField(choices=[('pay', '支付'), ('income', '收入')], help_text='是支付的记录还是收入的记录', verbose_name='购买类型'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='章节对应 ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter', verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='money',
            field=models.FloatField(default=0, help_text='涉及金额', verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='use_currency',
            field=models.IntegerField(choices=[('recharge', '充值币'), ('present', '赠币')], help_text='是哪一种货币，充值币还是赠币', verbose_name='使用货币'),
        ),
        migrations.AlterField(
            model_name='deallog',
            name='user',
            field=models.ForeignKey(help_text='用户对应 ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follow_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='关注时间', verbose_name='关注时间'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='book',
            field=models.ForeignKey(help_text='图书对应 ID', on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='purchased',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='章节对应 ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter', verbose_name='章节'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(help_text='城市', max_length=15, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='邮箱', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], help_text='性别', max_length=6, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(help_text='头像', upload_to='users/images', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduce',
            field=models.TextField(blank=True, default='', help_text='自我介绍', max_length=100, null=True, verbose_name='自我介绍'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='likes',
            field=models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(blank=True, help_text='我的签名', max_length=20, null=True, verbose_name='我的签名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(help_text='昵称', max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='province',
            field=models.CharField(help_text='省份', max_length=25, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='read_time',
            field=models.FloatField(default=0, help_text='阅读时间', verbose_name='阅读时间'),
        ),
    ]
