# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='图书名称')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('cover', models.ImageField(upload_to='books/cover', verbose_name='图书封面')),
                ('brief', models.TextField(blank=True, default='', verbose_name='图书简介')),
                ('word_count', models.IntegerField(default=0, verbose_name='总字数')),
                ('copyright', models.CharField(max_length=100, verbose_name='版权信息')),
                ('rank', models.FloatField(default=0, verbose_name='评分')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读人数')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新书')),
                ('is_index', models.BooleanField(default=False, verbose_name='是否在首页显示')),
                ('is_end', models.BooleanField(default=False, verbose_name='是否完结')),
            ],
            options={
                'verbose_name': '公共图书',
                'verbose_name_plural': '公共图书',
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='截取文本')),
                ('index', models.IntegerField(default=0, verbose_name='字符位置')),
            ],
            options={
                'verbose_name': '书签',
                'verbose_name_plural': '书签',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='类别')),
            ],
            options={
                'verbose_name': '图书类别',
                'verbose_name_plural': '图书类别',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='章节名')),
                ('index', models.IntegerField(verbose_name='章节号')),
                ('content', models.TextField(verbose_name='内容')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='CollectionBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_time', models.FloatField(default=0, verbose_name='阅读时长')),
                ('start_read_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始阅读时间')),
                ('is_finish', models.BooleanField(default=False, verbose_name='是否读完')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='图书')),
            ],
            options={
                'verbose_name': '藏书',
                'verbose_name_plural': '藏书',
            },
        ),
    ]
