# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180114_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='book',
            field=models.ForeignKey(help_text='图书对应的 ID', on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='books.Book', verbose_name='图书'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='index',
            field=models.IntegerField(default=0, help_text='字符位置', verbose_name='字符位置'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(help_text='用户对应的 ID', on_delete=django.db.models.deletion.CASCADE, related_name='my_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='collectionbook',
            name='is_finish',
            field=models.BooleanField(default=False, help_text='是否读完', verbose_name='是否读完'),
        ),
    ]
