# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180101_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copyright',
            field=models.CharField(blank=True, max_length=100, verbose_name='版权信息'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='books/cover', verbose_name='图书封面'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rank',
            field=models.FloatField(blank=True, default=0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_count',
            field=models.IntegerField(blank=True, default=0, verbose_name='阅读人数'),
        ),
    ]
