# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-19 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180119_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='desc',
            field=models.TextField(help_text='截取文本，以这段文本定位', verbose_name='截取文本'),
        ),
        migrations.AlterField(
            model_name='collectionbook',
            name='book',
            field=models.OneToOneField(help_text='图书对应 ID', on_delete=django.db.models.deletion.CASCADE, to='books.Book', verbose_name='图书'),
        ),
    ]
